In [5]:
import brazilian_bonds_db as bbdb

In [6]:
bbdb.update(data_root=r"Z:\Chila\projetos\calculadora_titulos_publicos")

2026-05-28 09:29:44 - app.lake.bronze.pipeline - INFO - === Bronze phase (10 datasets) ===
2026-05-28 09:29:46 - app.lake.bronze.pipeline - INFO - [mercado_secundario] Bronze success: candidates=8 processed=['2026-05-27'] rows=51 path=Z:\Chila\projetos\calculadora_titulos_publicos\lake\bronze\mercado_secundario\data=2026-05-27\part.json
2026-05-28 09:29:54 - app.lake.bronze.pipeline - INFO - [liquidacoes_mercado] Bronze success: candidates=8 processed=['2026-05-27'] rows=55 path=Z:\Chila\projetos\calculadora_titulos_publicos\lake\bronze\liquidacoes_mercado\data=2026-05-27\part.parquet
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Processing date: 2026-01-01
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Folder not found: X:\Interest_Rate\SettlementPrice\20260101\
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Skipping 2026-01-01 — file not found
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Processing date: 2026-02-16
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Folder not found: X:\Interest_Rate\SettlementPrice\20260216\
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Skipping 2026-02-16 — file not found
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Processing date: 2026-02-17
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Folder not found: X:\Interest_Rate\SettlementPrice\20260217\
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Skipping 2026-02-17 — file not found
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Processing date: 2026-04-03
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Folder not found: X:\Interest_Rate\SettlementPrice\20260403\
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Skipping 2026-04-03 — file not found
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Processing date: 2026-04-21
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Folder not found: X:\Interest_Rate\SettlementPrice\20260421\
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Skipping 2026-04-21 — file not found
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Processing date: 2026-05-01
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Folder not found: X:\Interest_Rate\SettlementPrice\20260501\
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Skipping 2026-05-01 — file not found
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Processing date: 2026-05-27
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Found 3 files with prefix Interest_Rate_SettlementPriceFile_Futures_20260527_
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Using newest file: Interest_Rate_SettlementPriceFile_Futures_20260527_3.csv
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Date 2026-05-27 loaded OK. 243 rows.
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Processing date: 2026-05-28
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Folder not found: X:\Interest_Rate\SettlementPrice\20260528\
2026-05-28 09:29:55 - app.providers.uptodata.client - WARNING - Skipping 2026-05-28 — file not found
2026-05-28 09:29:55 - app.providers.uptodata.client - INFO - Total rows in combined frame: 243
2026-05-28 09:29:55 - app.lake.bronze.pipeline - INFO - [ajustes_bmf] Bronze success: candidates=8 processed=['2026-05-27'] rows=243 path=Z:\Chila\projetos\calculadora_titulos_publicos\lake\bronze\ajustes_bmf\data=2026-05-27\part.parquet
2026-05-28 09:29:55 - app.providers.tesouro.client - INFO - Treasury results API: fetching years=[2026] (requested_dates=65)
2026-05-28 09:29:57 - app.lake.bronze.pipeline - INFO - [leiloes] Bronze skipped: candidates=65 processed=[] rows=0 path=None
2026-05-28 09:29:57 - app.lake.bronze.pipeline - INFO - [ipca_indice] Bronze skipped: candidates=9 processed=[] rows=0 path=None
2026-05-28 09:29:58 - app.lake.bronze.pipeline - INFO - [projecoes] Bronze success: candidates=5 processed=['2026-04-01', '2026-05-01', '2026-06-01'] rows=26 path=Z:\Chila\projetos\calculadora_titulos_publicos\lake\bronze\projecoes\reference_month=2026-06-01\part.json
2026-05-28 09:29:58 - app.lake.bronze.pipeline - INFO - [feriados] Bronze skipped: candidates=0 processed=[] rows=0 path=None
2026-05-28 09:30:00 - app.lake.bronze.pipeline - INFO - [cdi] Bronze success: candidates=8 processed=['2026-05-27'] rows=1 path=Z:\Chila\projetos\calculadora_titulos_publicos\lake\bronze\cdi\data=2026-05-27\part.parquet
2026-05-28 09:30:02 - app.lake.bronze.pipeline - INFO - [ptax] Bronze success: candidates=8 processed=['2026-05-27'] rows=1 path=Z:\Chila\projetos\calculadora_titulos_publicos\lake\bronze\ptax\data=2026-05-27\part.parquet
2026-05-28 09:30:04 - app.lake.bronze.pipeline - INFO - [vna] Bronze success: candidates=7 processed=['2026-05-28'] rows=1 path=Z:\Chila\projetos\calculadora_titulos_publicos\lake\bronze\vna\data=2026-05-28\part.json
2026-05-28 09:30:04 - app.lake.bronze.pipeline - INFO - === Bronze phase completed ===
2026-05-28 09:30:09 - app.lake.silver.pipeline - INFO - === Silver phase (7 datasets) ===
2026-05-28 09:30:09 - app.lake.silver.pipeline - INFO - [mercado_secundario] Silver success: candidates=1 processed=['2026-05-27'] rows=51
2026-05-28 09:30:10 - app.lake.silver.pipeline - INFO - [liquidacoes_mercado] Silver success: candidates=1 processed=['2026-05-27'] rows=55
2026-05-28 09:30:10 - app.lake.silver.pipeline - INFO - [ajustes_bmf] Silver success: candidates=1 processed=['2026-05-27'] rows=69
2026-05-28 09:30:10 - app.lake.silver.pipeline - INFO - [projecoes] Silver success: candidates=2 processed=['2026-04-01', '2026-05-01'] rows=20
2026-05-28 09:30:10 - app.lake.silver.pipeline - INFO - [cdi] Silver success: candidates=1 processed=['2026-05-27'] rows=1
2026-05-28 09:30:10 - app.lake.silver.pipeline - INFO - [ptax] Silver success: candidates=1 processed=['2026-05-27'] rows=1
2026-05-28 09:30:10 - app.lake.silver.pipeline - INFO - [vna] Silver success: candidates=1 processed=['2026-05-28'] rows=3
2026-05-28 09:30:10 - app.lake.silver.pipeline - INFO - === Silver phase completed ===

feriados: items=1263
  persisted_rows=1263
cdi: rows=1 columns=2
  range: 2026-05-27 .. 2026-05-27
  persisted_rows=1
ptax: rows=1 columns=3
  range: 2026-05-27 .. 2026-05-27
  persisted_rows=1
bmf: rows=69 columns=6
  range: 2026-05-27 .. 2026-05-27
  persisted_rows=69
mercado_secundario: rows=51 columns=17
  range: 2026-05-27 .. 2026-05-27
  persisted_rows=51
liquidacoes_mercado: rows=50 columns=11
  range: 2026-05-27 .. 2026-05-27
  persisted_rows=50
ipca_dict: rows=1 columns=16
  range: 2026-05-28 .. 2026-05-28
  persisted_rows=1
vna: rows=3 columns=7
  range: 2026-05-28 .. 2026-05-28
  persisted_rows=3

UpdateDatabaseResult(data_root=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos'), db_path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/database/app.db'), environment=LocalEnvironment(data_root=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos'), database_dir=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/database'), sqlite_db_path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/database/app.db'), lake_root=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake'), bronze_root=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/bronze'), silver_root=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/silver'), gold_root=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/gold'), logs_dir=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/logs'), metadata_dir=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/metadata')), migration=MigrationRunResult(db_path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/database/app.db'), newly_applied=(), total_applied=('001', '002', '003', '004', '005', '006', '007', '008', '009', '010', '011', '012')), gaps_before={'bronze': {'cdi': ['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-27', '2026-05-28'], 'ptax': ['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-27', '2026-05-28'], 'ipca_indice': ['2026-05-01'], 'mercado_secundario': ['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-27', '2026-05-28'], 'liquidacoes_mercado': ['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-27', '2026-05-28']}, 'silver': {}, 'gold': {'ipca_dict': ['2026-05-28']}}, gaps_after={'bronze': {'cdi': ['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-28'], 'ptax': ['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-28'], 'ipca_indice': ['2026-05-01'], 'mercado_secundario': ['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-28'], 'liquidacoes_mercado': ['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-28']}, 'silver': {}, 'gold': {}}, sync_ran=True, sync_phases=(SyncPhaseResult(name='bronze', task_count=10, details={'mercado_secundario': BronzeResult(name='mercado_secundario', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/bronze/mercado_secundario/data=2026-05-27/part.json'), row_count=51, segment_keys=['2026-05-27'], dates_candidate=['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-27', '2026-05-28'], error=None), 'liquidacoes_mercado': BronzeResult(name='liquidacoes_mercado', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/bronze/liquidacoes_mercado/data=2026-05-27/part.parquet'), row_count=55, segment_keys=['2026-05-27'], dates_candidate=['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-27', '2026-05-28'], error=None), 'ajustes_bmf': BronzeResult(name='ajustes_bmf', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/bronze/ajustes_bmf/data=2026-05-27/part.parquet'), row_count=243, segment_keys=['2026-05-27'], dates_candidate=['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-27', '2026-05-28'], error=None), 'leiloes': BronzeResult(name='leiloes', status='skipped', path=None, row_count=0, segment_keys=[], dates_candidate=['2026-01-01', '2026-01-02', '2026-01-05', '2026-01-07', '2026-01-09', '2026-01-12', '2026-01-14', '2026-01-16', '2026-01-19', '2026-01-21', '2026-01-23', '2026-01-26', '2026-01-28', '2026-01-30', '2026-02-02', '2026-02-04', '2026-02-06', '2026-02-09', '2026-02-11', '2026-02-13', '2026-02-16', '2026-02-17', '2026-02-18', '2026-02-20', '2026-02-23', '2026-02-25', '2026-02-27', '2026-03-02', '2026-03-04', '2026-03-06', '2026-03-09', '2026-03-11', '2026-03-13', '2026-03-19', '2026-03-20', '2026-03-23', '2026-03-25', '2026-03-27', '2026-03-30', '2026-04-01', '2026-04-03', '2026-04-06', '2026-04-08', '2026-04-10', '2026-04-13', '2026-04-15', '2026-04-17', '2026-04-20', '2026-04-21', '2026-04-24', '2026-04-27', '2026-04-29', '2026-05-01', '2026-05-04', '2026-05-06', '2026-05-08', '2026-05-11', '2026-05-13', '2026-05-15', '2026-05-18', '2026-05-20', '2026-05-22', '2026-05-25', '2026-05-27', '2026-05-28'], error=None), 'ipca_indice': BronzeResult(name='ipca_indice', status='skipped', path=None, row_count=0, segment_keys=[], dates_candidate=['2025-09-01', '2025-10-01', '2025-11-01', '2025-12-01', '2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01', '2026-05-01'], error=None), 'projecoes': BronzeResult(name='projecoes', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/bronze/projecoes/reference_month=2026-06-01/part.json'), row_count=26, segment_keys=['2026-04-01', '2026-05-01', '2026-06-01'], dates_candidate=['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01', '2026-05-01'], error=None), 'feriados': BronzeResult(name='feriados', status='skipped', path=None, row_count=0, segment_keys=[], dates_candidate=[], error=None), 'cdi': BronzeResult(name='cdi', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/bronze/cdi/data=2026-05-27/part.parquet'), row_count=1, segment_keys=['2026-05-27'], dates_candidate=['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-27', '2026-05-28'], error=None), 'ptax': BronzeResult(name='ptax', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/bronze/ptax/data=2026-05-27/part.parquet'), row_count=1, segment_keys=['2026-05-27'], dates_candidate=['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-27', '2026-05-28'], error=None), 'vna': BronzeResult(name='vna', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/bronze/vna/data=2026-05-28/part.json'), row_count=1, segment_keys=['2026-05-28'], dates_candidate=['2026-01-01', '2026-02-16', '2026-02-17', '2026-04-03', '2026-04-21', '2026-05-01', '2026-05-28'], error=None)}), SyncPhaseResult(name='silver', task_count=7, details={'mercado_secundario': SilverResult(name='mercado_secundario', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/silver/mercado_secundario/data=2026-05-27/part.parquet'), row_count=51, segment_keys=['2026-05-27'], dates_candidate=['2026-05-27'], error=None), 'liquidacoes_mercado': SilverResult(name='liquidacoes_mercado', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/silver/liquidacoes_mercado/data=2026-05-27/part.parquet'), row_count=55, segment_keys=['2026-05-27'], dates_candidate=['2026-05-27'], error=None), 'ajustes_bmf': SilverResult(name='ajustes_bmf', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/silver/ajustes_bmf/data=2026-05-27/part.parquet'), row_count=69, segment_keys=['2026-05-27'], dates_candidate=['2026-05-27'], error=None), 'projecoes': SilverResult(name='projecoes', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/silver/projecoes/reference_month=2026-05-01/part.parquet'), row_count=20, segment_keys=['2026-04-01', '2026-05-01'], dates_candidate=['2026-04-01', '2026-05-01'], error=None), 'cdi': SilverResult(name='cdi', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/silver/cdi/data=2026-05-27/part.parquet'), row_count=1, segment_keys=['2026-05-27'], dates_candidate=['2026-05-27'], error=None), 'ptax': SilverResult(name='ptax', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/silver/ptax/data=2026-05-27/part.parquet'), row_count=1, segment_keys=['2026-05-27'], dates_candidate=['2026-05-27'], error=None), 'vna': SilverResult(name='vna', status='success', path=WindowsPath('Z:/Chila/projetos/calculadora_titulos_publicos/lake/silver/vna/data=2026-05-28/part.parquet'), row_count=3, segment_keys=['2026-05-28'], dates_candidate=['2026-05-28'], error=None)}), SyncPhaseResult(name='gold', task_count=8, details=[GoldMaterialized(name='feriados', silver={'feriados':             data
0     2001-01-01
1     2001-02-26
2     2001-02-27
3     2001-04-13
4     2001-04-21
...          ...
1258  2099-10-12
1259  2099-11-02
1260  2099-11-15
1261  2099-11-20
1262  2099-12-25


In [7]:
reader = bbdb.read_data(db_path=r"Z:\Chila\projetos\calculadora_titulos_publicos\database\app.db")

In [8]:
reader.ipca_dict.fetch_latest(5)

,data_referencia,ultimo_mes_ipca,ref_month_atual,ref_month_anterior,indice_ipca_data_base,indice_ipca_fechado_atual,indice_ipca_fechado_anterior,var_ipca_atual,var_ipca_ant,ipca_proj,ipca_usado,usa_fechado,data_coleta_referencia,ipca_proj_data_coleta,inicio_mes_ipca,fim_mes_ipca
0,2026-05-28,4,2026-04-01,2026-03-01,1614.62,7596.09,7545.53,0.67,0.88,0.5,0.5,0,2026-05-27,2026-05-27,2026-05-15,2026-06-15
1,2026-05-27,4,2026-04-01,2026-03-01,1614.62,7596.09,7545.53,0.67,0.88,0.5,0.5,0,2026-05-12,2026-05-12,2026-05-15,2026-06-15
2,2026-05-26,4,2026-04-01,2026-03-01,1614.62,7596.09,7545.53,0.67,0.88,0.5,0.5,0,2026-05-12,2026-05-12,2026-05-15,2026-06-15
3,2026-05-25,4,2026-04-01,2026-03-01,1614.62,7596.09,7545.53,0.67,0.88,0.5,0.5,0,2026-05-12,2026-05-12,2026-05-15,2026-06-15
4,2026-05-24,4,2026-04-01,2026-03-01,1614.62,7596.09,7545.53,0.67,0.88,0.5,0.5,0,2026-05-12,2026-05-12,2026-05-15,2026-06-15

In [21]:
from pathlib import Path

import pandas as pd

caminho = Path(
    r"Z:\Chila\projetos\calculadora_titulos_publicos\lake\silver\ajustes_bmf\data=2026-05-22\part.parquet"
)

df = pd.read_parquet(caminho)
df

,data_referencia,ticker,SctyId,SctySrc,MktIdrCd,codigo_isin,data_vencimento,quantidade_ajuste,taxa_ajuste,AdjstdQtStin,PrvsAdjstdQt,PrvsAdjstdQtTax,PrvsAdjstdQtStin,VartnPts,EqvtVal,AdjstdValCtrct,DataSts
0,2026-05-22,DAPF27,200001817282,8,BVMF,BRBMEFDAP4Y9,2027-01-15,94387.98,9.340,F,94404.94,9.310,U,-16.96,NaN,-32.247617,I
1,2026-05-22,DAPK27,100000164464,8,BVMF,BRBMEFDAP3U9,2027-05-17,92582.40,8.250,F,92571.21,8.263,U,11.19,NaN,21.276582,I
2,2026-05-22,DAPK29,200001361511,8,BVMF,BRBMEFDAP4N2,2029-05-15,79936.62,7.880,F,79979.09,7.861,U,-42.47,NaN,-80.752139,I
3,2026-05-22,DAPK31,300000055944,8,BVMF,BRBMEFDAP5E8,2031-05-15,68799.54,7.870,F,68829.91,7.860,U,-30.37,NaN,-57.745290,I
4,2026-05-22,DAPK33,100000191028,8,BVMF,BRBMEFDAP462,2033-05-16,59471.57,7.775,F,59470.78,7.775,U,0.79,NaN,1.502100,I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,2026-05-22,DI1X29,100000250791,8,BVMF,BRBMEFD1I8Z1,2029-11-01,63986.63,13.926,F,63954.95,13.942,U,31.68,NaN,31.680000,N
64,2026-05-22,DI1Z26,400000105486,8,BVMF,BRBMEFD1I8O5,2026-12-01,93316.27,14.118,F,93330.55,14.085,U,-14.28,NaN,-14.280000,N
65,2026-05-22,DI1Z27,100000250768,8,BVMF,BRBMEFD1I8W8,2027-12-01,82155.22,13.845,F,82186.43,13.816,U,-31.21,NaN,-31.210000,N
66,2026-05-22,DI1Z28,100000250782,8,BVMF,BRBMEFD1I8Y4,2028-12-01,72202.84,13.844,F,72215.40,13.836,U,-12.56,NaN,-12.560000,N
67,2026-05-22,DI1Z29,100000250792,8,BVMF,BRBMEFD1I900,2029-12-03,63358.76,13.927,F,63318.89,13.947,U,39.87,NaN,39.870000,N